from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import joblib
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.decomposition import TruncatedSVD
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier, StackingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_ROOT = PROJECT_ROOT / "Source_Code"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from evaluation.advanced_metrics import compute_advanced_metrics
from feature_engineering.cnn_feature_names import is_cnn_feature


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run phased experiments for multi-model child-safety video classification."
    )
    parser.add_argument(
        "--csv",
        default="Feature_Files/video_features_advanced.csv",
        help="Video-only feature CSV generated by build_video_only_features.py.",
    )
    parser.add_argument(
        "--output-dir",
        default="Models/artifacts_phase1",
        help="Directory where reports, plots, and models will be saved.",
    )
    parser.add_argument(
        "--test-size",
        type=float,
        default=0.3,
        help="Test split ratio.",
    )
    parser.add_argument(
        "--random-state",
        type=int,
        default=42,
        help="Random seed for reproducibility.",
    )
    return parser.parse_args()


def ensure_required_columns(df: pd.DataFrame) -> pd.DataFrame:
    prepared = df.copy()

    if "label" not in prepared.columns:
        raise ValueError("Input CSV must contain a 'label' column.")

    return prepared


def detect_feature_groups(df: pd.DataFrame) -> list[str]:
    excluded = {
        "label",
        "video_name",
        "video_path",
        "class_name",
    }
    visual_columns = [
        column
        for column in df.columns
        if column not in excluded and pd.api.types.is_numeric_dtype(df[column])
    ]
    return visual_columns


def build_numeric_only_preprocessor(columns: list[str]) -> ColumnTransformer:
    return ColumnTransformer(
        transformers=[
            (
                "numeric",
                Pipeline(
                    steps=[
                        ("imputer", SimpleImputer(strategy="constant", fill_value=0)),
                        ("scaler", StandardScaler()),
                    ]
                ),
                columns,
            )
        ],
        remainder="drop",
    )


def build_xgboost(random_state: int) -> XGBClassifier:
    return XGBClassifier(
        n_estimators=250,
        max_depth=5,
        learning_rate=0.05,
        subsample=0.9,
        colsample_bytree=0.9,
        eval_metric="logloss",
        random_state=random_state,
    )


def build_model_suite(random_state: int) -> dict[str, object]:
    return {
        "logistic_regression": LogisticRegression(max_iter=3000, random_state=random_state),
        "decision_tree": DecisionTreeClassifier(
            max_depth=8,
            min_samples_leaf=3,
            class_weight="balanced",
            random_state=random_state,
        ),
        "random_forest": RandomForestClassifier(
            n_estimators=300,
            max_depth=None,
            min_samples_leaf=2,
            class_weight="balanced",
            random_state=random_state,
            n_jobs=-1,
        ),
        "svm_rbf": SVC(
            kernel="rbf",
            C=2.0,
            gamma="scale",
            probability=True,
            class_weight="balanced",
            random_state=random_state,
        ),
        "knn": KNeighborsClassifier(n_neighbors=7),
        "naive_bayes": GaussianNB(),
        "adaboost": AdaBoostClassifier(n_estimators=150, learning_rate=0.5, random_state=random_state),
        "xgboost": build_xgboost(random_state),
        "mlp_classifier": MLPClassifier(
            hidden_layer_sizes=(64, 32),
            activation="relu",
            alpha=0.001,
            learning_rate_init=0.001,
            early_stopping=True,
            validation_fraction=0.15,
            max_iter=600,
            random_state=random_state,
        ),
    }


def build_stacking_classifier(random_state: int) -> StackingClassifier:
    return StackingClassifier(
        estimators=[
            (
                "rf",
                RandomForestClassifier(
                    n_estimators=250,
                    min_samples_leaf=2,
                    class_weight="balanced",
                    random_state=random_state,
                    n_jobs=-1,
                ),
            ),
            (
                "svm",
                SVC(
                    kernel="rbf",
                    C=2.0,
                    gamma="scale",
                    probability=True,
                    class_weight="balanced",
                    random_state=random_state,
                ),
            ),
            ("xgb", build_xgboost(random_state)),
            (
                "mlp",
                MLPClassifier(
                    hidden_layer_sizes=(64, 32),
                    activation="relu",
                    alpha=0.001,
                    learning_rate_init=0.001,
                    early_stopping=True,
                    validation_fraction=0.15,
                    max_iter=600,
                    random_state=random_state,
                ),
            ),
        ],
        final_estimator=LogisticRegression(max_iter=3000, random_state=random_state),
        stack_method="predict_proba",
        cv=5,
        n_jobs=-1,
        passthrough=False,
    )


def save_confusion_matrix(matrix: np.ndarray, labels: list[str], title: str, path: Path) -> None:
    fig, ax = plt.subplots(figsize=(5, 4))
    im = ax.imshow(matrix, cmap="Blues")
    ax.set_xticks(range(len(labels)))
    ax.set_yticks(range(len(labels)))
    ax.set_xticklabels(labels)
    ax.set_yticklabels(labels)
    ax.set_xlabel("Predicted label")
    ax.set_ylabel("True label")
    ax.set_title(title)

    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            ax.text(j, i, matrix[i, j], ha="center", va="center", color="black")

    fig.colorbar(im, ax=ax)
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def describe_fit(train_accuracy: float, test_accuracy: float) -> str:
    gap = train_accuracy - test_accuracy
    if train_accuracy >= 0.95 and gap >= 0.1:
        return "cv_review"
    if train_accuracy < 0.65 and test_accuracy < 0.65:
        return "low_fit"
    if abs(gap) <= 0.05:
        return "stable_fit"
    return "moderate_gap"


def evaluate_pipeline(
    *,
    name: str,
    estimator: Pipeline,
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
    y_train: pd.Series,
    y_test: pd.Series,
    output_dir: Path,
) -> dict[str, float | str]:
    model = clone(estimator)
    model.fit(X_train, y_train)

    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)
    test_proba = model.predict_proba(X_test) if hasattr(model, "predict_proba") else None

    train_accuracy = accuracy_score(y_train, train_pred)
    test_accuracy = accuracy_score(y_test, test_pred)
    precision = precision_score(y_test, test_pred, zero_division=0)
    recall = recall_score(y_test, test_pred, zero_division=0)
    f1 = f1_score(y_test, test_pred, zero_division=0)
    matrix = confusion_matrix(y_test, test_pred)

    predictions = pd.DataFrame(
        {
            "true_label": y_test.to_numpy(),
            "predicted_label": test_pred,
        }
    )
    predictions.to_csv(output_dir / f"{name}_predictions.csv", index=False)

    save_confusion_matrix(
        matrix,
        labels=["safe", "unsafe"],
        title=f"{name.replace('_', ' ').title()} Confusion Matrix",
        path=output_dir / f"{name}_confusion_matrix.png",
    )

    joblib.dump(model, output_dir / f"{name}_model.joblib")

    metrics = {
        "phase": name,
        "train_accuracy": round(train_accuracy, 4),
        "test_accuracy": round(test_accuracy, 4),
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1_score": round(f1, 4),
        "fit_status": describe_fit(train_accuracy, test_accuracy),
    }
    advanced = compute_advanced_metrics(y_test, test_pred, test_proba)
    for key in ("specificity", "mcc", "roc_auc", "pr_auc", "log_loss"):
        if key in advanced:
            metrics[key] = advanced[key]

    (output_dir / f"{name}_classification_report.txt").write_text(
        classification_report(y_test, test_pred, target_names=["safe", "unsafe"]),
        encoding="utf-8",
    )

    return metrics


def write_phase1_report(
    *,
    df: pd.DataFrame,
    visual_columns: list[str],
    metrics_df: pd.DataFrame,
    analysis: dict[str, float | str],
    output_dir: Path,
) -> None:
    class_counts = df["label"].value_counts().sort_index()
    best = metrics_df.sort_values(["test_accuracy", "f1_score"], ascending=False).iloc[0]
    report = f"""# Project Report: Safe and Unsafe Video Activity Classification

## Dataset and Preprocessing
- Dataset file: `{df.attrs.get("source_csv", "input csv")}`
- Total videos represented: {len(df)}
- Safe videos (`label=0`): {int(class_counts.get(0, 0))}
- Unsafe videos (`label=1`): {int(class_counts.get(1, 0))}
- Video/CNN features used: {len(visual_columns)}
- Missing values are handled with `SimpleImputer`.
- Numeric video features are standardized with `StandardScaler`.
- The train/test split is stratified, so both classes remain balanced in evaluation.

## Feature Reliability
This project does **not** decide child safety using only brightness, darkness, or video color.
The main visual representation is a pretrained CNN embedding with named groups such as `edge_texture_feature_001`, `object_body_feature_001`, `scene_activity_feature_001`, and `safety_context_feature_001`.
Brightness alone is not used as a safety rule because a black shirt, black paint, or a dark background does not make a video unsafe.

## Models Implemented
- Logistic Regression baseline
- Decision Tree
- Random Forest
- Support Vector Machine with RBF kernel
- XGBoost
- K-Nearest Neighbors
- Naive Bayes
- AdaBoost
- MLP Classifier
- KNN sweep for comparison
- Stacking Classifier combining Random Forest, SVM, XGBoost, and MLP with Logistic Regression as the final estimator

## Best Result
- Best model: `{best["phase"]}`
- Test accuracy: {float(best["test_accuracy"]):.4f}
- Precision: {float(best["precision"]):.4f}
- Recall: {float(best["recall"]):.4f}
- F1 score: {float(best["f1_score"]):.4f}
- Generalization status: `{best["fit_status"]}`

## Analysis
- Inter-class distance: {analysis.get("inter_class_distance", "N/A")}
- Mean intra-class spread: {analysis.get("mean_intra_class_spread", "N/A")}
- Separability verdict: {analysis.get("separability_verdict", "N/A")}

## Conclusion
The project demonstrates dataset preparation, preprocessing, multiple ML models, the required stacking classifier, and result analysis with saved metrics, reports, predictions, model files, and confusion matrices.
"""
    (output_dir / "PHASE1_PROJECT_REPORT.md").write_text(report, encoding="utf-8")


def compute_class_separability(
    X: pd.DataFrame,
    y: pd.Series,
    visual_columns: list[str],
) -> dict[str, float | str]:
    numeric_columns = visual_columns
    if not numeric_columns:
        return {"separability_note": "No numeric features available for separability analysis."}

    numeric = X[numeric_columns].fillna(0)
    safe_vectors = numeric[y == 0]
    unsafe_vectors = numeric[y == 1]

    if safe_vectors.empty or unsafe_vectors.empty:
        return {"separability_note": "Both classes are required for separability analysis."}

    safe_centroid = safe_vectors.mean(axis=0).to_numpy()
    unsafe_centroid = unsafe_vectors.mean(axis=0).to_numpy()

    inter_class_distance = float(np.linalg.norm(safe_centroid - unsafe_centroid))
    intra_safe = float(np.linalg.norm(safe_vectors.to_numpy() - safe_centroid, axis=1).mean())
    intra_unsafe = float(np.linalg.norm(unsafe_vectors.to_numpy() - unsafe_centroid, axis=1).mean())
    mean_intra_class_spread = (intra_safe + intra_unsafe) / 2.0

    return {
        "inter_class_distance": round(inter_class_distance, 4),
        "mean_intra_class_spread": round(mean_intra_class_spread, 4),
        "separability_verdict": "good"
        if inter_class_distance > mean_intra_class_spread
        else "weak",
    }


def run_knn_sweep(
    *,
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
    y_train: pd.Series,
    y_test: pd.Series,
    preprocessor: ColumnTransformer,
    output_dir: Path,
    random_state: int,
) -> pd.DataFrame:
    fitted_preprocessor = clone(preprocessor)
    X_train_features = fitted_preprocessor.fit_transform(X_train, y_train)
    X_test_features = fitted_preprocessor.transform(X_test)

    feature_count = X_train_features.shape[1]
    sample_count = X_train_features.shape[0]
    max_components = min(50, feature_count - 1, sample_count - 1)

    if max_components >= 2:
        reducer = TruncatedSVD(n_components=max_components, random_state=random_state)
        X_train_ready = reducer.fit_transform(X_train_features)
        X_test_ready = reducer.transform(X_test_features)
    else:
        X_train_ready = X_train_features.toarray() if hasattr(X_train_features, "toarray") else X_train_features
        X_test_ready = X_test_features.toarray() if hasattr(X_test_features, "toarray") else X_test_features

    scaler = StandardScaler()
    X_train_ready = scaler.fit_transform(X_train_ready)
    X_test_ready = scaler.transform(X_test_ready)

    rows: list[dict[str, float | int]] = []

    for k in range(1, 12):
        model = KNeighborsClassifier(n_neighbors=k)
        model.fit(X_train_ready, y_train)
        y_pred = model.predict(X_test_ready)
        rows.append(
            {
                "k": k,
                "accuracy": round(accuracy_score(y_test, y_pred), 4),
                "f1_score": round(f1_score(y_test, y_pred, zero_division=0), 4),
            }
        )

    results = pd.DataFrame(rows)
    results.to_csv(output_dir / "knn_results.csv", index=False)

    best_row = results.sort_values(["accuracy", "f1_score"], ascending=False).iloc[0]
    best_k = int(best_row["k"])

    best_artifact = {
        "preprocessor": fitted_preprocessor,
        "scaler": scaler,
        "model": KNeighborsClassifier(n_neighbors=best_k).fit(X_train_ready, y_train),
        "used_svd": max_components >= 2,
        "svd": reducer if max_components >= 2 else None,
    }
    joblib.dump(best_artifact, output_dir / "best_knn_model.joblib")

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.plot(results["k"], results["accuracy"], marker="o")
    ax.set_xlabel("k")
    ax.set_ylabel("Accuracy")
    ax.set_title("KNN: k vs Accuracy")
    ax.set_xticks(results["k"])
    ax.grid(True, linestyle="--", alpha=0.4)
    fig.tight_layout()
    fig.savefig(output_dir / "knn_k_vs_accuracy.png")
    plt.close(fig)

    return results


def main() -> None:
    args = parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    df = ensure_required_columns(pd.read_csv(args.csv))
    df.attrs["source_csv"] = args.csv
    visual_columns = detect_feature_groups(df)

    metadata_columns = [column for column in ("video_name", "video_path", "class_name") if column in df.columns]
    X = df.drop(columns=["label"])
    y = df["label"]

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=args.test_size,
        stratify=y,
        random_state=args.random_state,
    )

    split_summary = {
        "train_samples": int(len(X_train)),
        "test_samples": int(len(X_test)),
        "safe_train": int((y_train == 0).sum()),
        "unsafe_train": int((y_train == 1).sum()),
        "safe_test": int((y_test == 0).sum()),
        "unsafe_test": int((y_test == 1).sum()),
    }
    (output_dir / "split_summary.json").write_text(
        json.dumps(split_summary, indent=2),
        encoding="utf-8",
    )

    experiments: list[tuple[str, Pipeline]] = []

    model_suite = build_model_suite(args.random_state)

    if visual_columns:
        visual_only_preprocessor = build_numeric_only_preprocessor(visual_columns)
        experiments.extend(
            [
                (
                    "phase1_visual_logistic",
                    Pipeline(steps=[("preprocessor", visual_only_preprocessor), ("model", model_suite["logistic_regression"])]),
                ),
                (
                    "phase2_visual_decision_tree",
                    Pipeline(steps=[("preprocessor", visual_only_preprocessor), ("model", model_suite["decision_tree"])]),
                ),
                (
                    "phase3_visual_random_forest",
                    Pipeline(steps=[("preprocessor", visual_only_preprocessor), ("model", model_suite["random_forest"])]),
                ),
                (
                    "phase4_visual_svm",
                    Pipeline(steps=[("preprocessor", visual_only_preprocessor), ("model", model_suite["svm_rbf"])]),
                ),
                (
                    "phase5_visual_knn",
                    Pipeline(steps=[("preprocessor", visual_only_preprocessor), ("model", model_suite["knn"])]),
                ),
                (
                    "phase6_visual_naive_bayes",
                    Pipeline(steps=[("preprocessor", visual_only_preprocessor), ("model", model_suite["naive_bayes"])]),
                ),
                (
                    "phase7_visual_adaboost",
                    Pipeline(steps=[("preprocessor", visual_only_preprocessor), ("model", model_suite["adaboost"])]),
                ),
                (
                    "phase8_visual_xgboost",
                    Pipeline(steps=[("preprocessor", visual_only_preprocessor), ("model", model_suite["xgboost"])]),
                ),
                (
                    "phase9_visual_mlp_classifier",
                    Pipeline(steps=[("preprocessor", visual_only_preprocessor), ("model", model_suite["mlp_classifier"])]),
                ),
                (
                    "phase10_visual_stacking_classifier",
                    Pipeline(
                        steps=[
                            ("preprocessor", visual_only_preprocessor),
                            ("model", build_stacking_classifier(args.random_state)),
                        ]
                    ),
                ),
            ]
        )

    if not experiments:
        raise SystemExit("No valid experiments could be built from the provided CSV.")

    metrics_rows: list[dict[str, float | str]] = []
    for name, estimator in experiments:
        metrics_rows.append(
            evaluate_pipeline(
                name=name,
                estimator=estimator,
                X_train=X_train,
                X_test=X_test,
                y_train=y_train,
                y_test=y_test,
                output_dir=output_dir,
            )
        )

    metrics_df = pd.DataFrame(metrics_rows).sort_values("test_accuracy", ascending=False)
    metrics_df.to_csv(output_dir / "metrics_summary.csv", index=False)

    preprocessor_for_knn = build_numeric_only_preprocessor(visual_columns)
    knn_results = run_knn_sweep(
        X_train=X_train,
        X_test=X_test,
        y_train=y_train,
        y_test=y_test,
        preprocessor=preprocessor_for_knn,
        output_dir=output_dir,
        random_state=args.random_state,
    )

    analysis = compute_class_separability(X, y, visual_columns)
    analysis["best_knn_k"] = int(knn_results.sort_values(["accuracy", "f1_score"], ascending=False).iloc[0]["k"])
    analysis["best_knn_accuracy"] = float(knn_results["accuracy"].max())
    (output_dir / "analysis_summary.json").write_text(
        json.dumps(analysis, indent=2),
        encoding="utf-8",
    )

    write_phase1_report(
        df=df,
        visual_columns=visual_columns,
        metrics_df=metrics_df,
        analysis=analysis,
        output_dir=output_dir,
    )

    if metadata_columns:
        test_export = X_test[metadata_columns].copy()
        test_export["true_label"] = y_test.to_numpy()
        test_export.to_csv(output_dir / "test_split_metadata.csv", index=False)

    print("Finished running experiments.")
    print(metrics_df.to_string(index=False))
    print()
    print("Best KNN result:")
    print(knn_results.sort_values(["accuracy", "f1_score"], ascending=False).head(1).to_string(index=False))


if __name__ == "__main__":
    main()
